Add Hexadecimal
bee-san/Ares pull request #140
Opened 2022-12-11 17:58 UTC by SkeletalDemise

Adds a hexadecimal decoder.

2022-12-11 18:31 UTC, bee-san requested changes

2022-12-11 18:31 UTC, bee-san commented on src/decoders/hexadecimal_decoder.rs
> +    let hex = hex.replace(|c: char| !c.is_ascii_hexdigit(), "");
If a string has non hex characters, does that mean it's not hex and we should skip it?

2022-12-11 18:43 UTC, SkeletalDemise commented on src/decoders/hexadecimal_decoder.rs
> +    }
Everything breaks when I do that, what's wrong with always returning a string? It's empty if it fails.

2022-12-11 18:48 UTC, bee-san commented on src/decoders/hexadecimal_decoder.rs
> +    }
> what's wrong with always returning a string? It's empty if it fails.

It is not the Rust way:tm: 

Change to this:

```rust
fn hexadecimal_to_string(hex: &str) -> Option<String> {
```

Return None, if it's okay return `Some(result)`

```rust
        trace!("Trying hexadecimal with text {:?}", text);
         let decoded_text = hexadecimal_to_string(text);
    if decoded_text.is_none() <-- fail the decoder
         let mut results = CrackResult::new(self, text.to_string());
         ```

2022-12-12 05:51 UTC, SkeletalDemise commented on src/decoders/hexadecimal_decoder.rs
> +    }
Done.

2022-12-12 08:36 UTC, merged