Improve Citrix CTX1
bee-san/Ares pull request #86
Opened 2022-11-17 13:18 UTC by SkeletalDemise

* Citrix CTX1 decoder now handles subtraction overflows
* Removed uppercase check, now it can decode lowercase Citrix CTX1 strings
* Added 3 more tests
* Removed 2 redundant tests
* Added docs to every test

2022-11-17 13:23 UTC, bee-san requested changes

2022-11-17 13:23 UTC, bee-san commented on src/decoders/citrix_ctx1_decoder.rs
> +            debug!("Failed to decode citrix_ctx1");
Anyway we can propagate an error here or something? Why couldn't it decode?

2022-11-17 13:23 UTC, bee-san commented on src/decoders/citrix_ctx1_decoder.rs
> +        // This tests if Citrix CTX1 can handle substraction overflows
```suggestion
    fn test_citrix_ctx1_handles_substraction_overflow() {
        // This tests if Citrix CTX1 can handle substraction overflows
```

2022-11-21 09:42 UTC, SkeletalDemise commented on src/decoders/citrix_ctx1_decoder.rs
> +        // This tests if Citrix CTX1 can decode Citrix CTX1 successfully
Done.

2022-11-21 09:43 UTC, SkeletalDemise commented on src/decoders/citrix_ctx1_decoder.rs
> +        // This tests if Citrix CTX1 can decode lowercase strings
Done.

2022-11-21 09:43 UTC, SkeletalDemise commented on src/decoders/citrix_ctx1_decoder.rs
> +        // This tests if Citrix CTX1 can handle substraction overflows
Done.

2022-11-21 09:43 UTC, SkeletalDemise commented on src/decoders/citrix_ctx1_decoder.rs
> +        // It should return None
Done.

2022-11-21 10:10 UTC, bee-san approved these changes

2022-11-21 10:10 UTC, merged